"""initial schema

Revision ID: 299a7dd37956
Revises: 
Create Date: 2026-07-13 05:10:37.947764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '299a7dd37956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('established_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_merchant_id'), 'connections', ['merchant_id'], unique=False)
    op.create_table('credit_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.String(length=2), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_assessments_merchant_id'), 'credit_assessments', ['merchant_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id')
    )
    op.create_index(op.f('ix_sales_orders_merchant_id'), 'sales_orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_date'), 'sales_orders', ['order_date'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delayed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id')
    )
    op.create_index(op.f('ix_settlements_expected_date'), 'settlements', ['expected_date'], unique=False)
    op.create_index(op.f('ix_settlements_merchant_id'), 'settlements', ['merchant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('account_external_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id')
    )
    op.create_index(op.f('ix_bank_accounts_merchant_id'), 'bank_accounts', ['merchant_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_connection_id'), 'consents', ['connection_id'], unique=False)
    op.create_index(op.f('ix_consents_session_id'), 'consents', ['session_id'], unique=True)
    op.create_table('financing_offers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('assessment_id', sa.String(length=32), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('advance_ratio', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('success_fee', sa.Float(), nullable=False),
    sa.Column('profit_amount', sa.Float(), nullable=False),
    sa.Column('total_repayable', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['credit_assessments.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financing_offers_merchant_id'), 'financing_offers', ['merchant_id'], unique=False)
    op.create_table('murabaha_contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('offer_id', sa.String(length=32), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('profit_amount', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('fees_total', sa.Float(), nullable=False),
    sa.Column('total_due', sa.Float(), nullable=False),
    sa.Column('outstanding', sa.Float(), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['financing_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_index(op.f('ix_murabaha_contracts_merchant_id'), 'murabaha_contracts', ['merchant_id'], unique=False)
    op.create_table('repayment_schedule_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('settlement_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_schedule_items_contract_id'), 'repayment_schedule_items', ['contract_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_merchant_id'), 'risk_alerts', ['merchant_id'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('schedule_item_id', sa.String(length=32), nullable=False),
    sa.Column('settlement_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['murabaha_contracts.id'], ),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['repayment_schedule_items.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_contract_id'), 'repayments', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayments_contract_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_risk_alerts_merchant_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_repayment_schedule_items_contract_id'), table_name='repayment_schedule_items')
    op.drop_table('repayment_schedule_items')
    op.drop_index(op.f('ix_murabaha_contracts_merchant_id'), table_name='murabaha_contracts')
    op.drop_table('murabaha_contracts')
    op.drop_index(op.f('ix_financing_offers_merchant_id'), table_name='financing_offers')
    op.drop_table('financing_offers')
    op.drop_index(op.f('ix_consents_session_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_connection_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_bank_accounts_merchant_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_settlements_merchant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_expected_date'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_sales_orders_order_date'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_merchant_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_credit_assessments_merchant_id'), table_name='credit_assessments')
    op.drop_table('credit_assessments')
    op.drop_index(op.f('ix_connections_merchant_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('system_state')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
